# Generated by Django 5.2.8 on 2025-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='event', to='events.participants'),
        ),
    ]
