# Generated by Django 5.2.8 on 2025-12-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
